# Generated by Django 4.1 on 2022-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardapio",
            name="refeicoes",
            field=models.ManyToManyField(related_name="cardapio", to="core.refeicaoes"),
        ),
        migrations.AlterField(
            model_name="refeicaoes",
            name="tituloref",
            field=models.CharField(max_length=200),
        ),
    ]
