# Generated by Django 4.1 on 2022-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refeicoes",
            name="alimentos",
            field=models.ManyToManyField(related_name="alimentos", to="core.alimento"),
        ),
    ]
