# Generated by Django 4.1 on 2022-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_refeicoes_alimentos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardapio",
            name="refeiçoes",
            field=models.ManyToManyField(
                null=True, related_name="refeiçoes", to="core.refeicoes"
            ),
        ),
    ]
