# Generated by Django 4.1 on 2022-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_cardapio_refeiçoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardapio",
            name="refeiçoes",
            field=models.ManyToManyField(related_name="refeiçoes", to="core.refeicoes"),
        ),
    ]
