# Generated by Django 4.1 on 2022-10-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cardapio_refeiçoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='refeiçoes',
            new_name='refeicoes',
        ),
    ]
