# Generated by Django 4.1 on 2022-10-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_refeiçoes_cardapio_refeicoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='refeicoes',
        ),
        migrations.AddField(
            model_name='refeicoes',
            name='cardapios',
            field=models.ManyToManyField(related_name='cardapios', to='core.cardapio'),
        ),
    ]
