# Generated by Django 4.1 on 2022-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cardapio_refeicoes_refeicoes_cardapios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicoes',
            name='cardapios',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='refeicoes',
            field=models.ManyToManyField(related_name='refeiçoes', to='core.refeicoes'),
        ),
    ]
