# Generated by Django 4.1 on 2022-10-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cardapio_refeicoes_refeicoes_cardapios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicoes',
            name='cardapios',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='refeicoes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.refeicoes'),
            preserve_default=False,
        ),
    ]
