# Generated by Django 4.1 on 2022-10-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cardapio_refeicoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='refeicoes',
        ),
    ]
