# Generated by Django 4.1 on 2022-12-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_refeicoes_cardapios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicoes',
            name='horario_refeicao',
        ),
    ]
